### ISSUE TITLE
[FIX] 프로젝트 생성 API 연동 및 배포를 위한 준비

### ISSUE THREAD

**Issue by yoon-junseo** [Project-Boated/boated-FE#15]
## 설명
- 프로젝트 생성 API 확인 및 에러 처리
- 배포를 위한 next.config.js 수정 
- CreateBox storybook 수정

## ToDo
- [x] 프로젝트 생성 API 체크 및 에러 처리
- [x] next.config.js 수정
- [x] CreateBox storybook 수정
