### ISSUE TITLE
[FEAT] Task 상세 모달

### ISSUE THREAD

**Issue by yoon-junseo** [Project-Boated/boated-FE#32]
## 설명
- Task를 조회하는 모달 개발
- UI 개발

## ToDo
- [x] Task 이름
- [x] 배정할 팀원
   - [x] 선택된 팀원 목록 컴포넌트
   - [x] 드롭다운
   - [x] 추가하기 버튼
- [x] 마감기한
- [x] 레인 선택
- [x] 등록된 파일
   - [x] label
   - [x] input
   - [ ] 업로드된 파일명, 생성일 표시
   - [x] 드롭 다운 구현
- [x] Task 설명   
- [x] Task 생성하기 버튼
