### ISSUE TITLE
[FEAT] 프로젝트 상세 페이지 API 연동

### ISSUE THREAD

**Issue by yoon-junseo** [Project-Boated/boated-FE#35]
## 설명
- 프로젝트 상세 페이지 API 연동

## ToDo
- [x] /api/projects/{id}
- [x] /api/projects/{id}/crews
- [ ] 데이터 채우기
   - [x] 프로젝트 이름
   - [ ] 마감기한
      - [ ] 달력
      - [x] 시간
   - [x] 프로젝트 소개
   - [x] 팀원 관리
      - [x] 팀장
      - [x] 팀원   
- [x] InfoBox의 storybook 수정
