### ISSUE TITLE
[FEAT] Task 상세 모달에 API 연동

### ISSUE THREAD

**Issue by yoon-junseo** [Project-Boated/boated-FE#50]
## 설명
- Task 상세 모달에서 API 연동
- debounce 처리

## ToDo
- [ ] task 수정 요청 debounce 처리
- [x] task 조회 - GET /api/projects/{projectId}/kanban/lanes/tasks/{taskId}
- [x] task 수정 - PATCH /api/projects/{projectId}/kanban/lanes/tasks/{taskId}
