### ISSUE TITLE
[FIX] 칸반 페이지 이슈 해결

### ISSUE THREAD

**Issue by SaaaHoP** [Project-Boated/boated-FE#51]
## 설명

- 칸반 페이지 이슈 해결

<hr />

## ToDo

- [x] Task 옮기면 바로 반영되게
- [x] Task 즐겨찾기 바로 반영되게
- [x] Task 삭제 바로 반영되게
- [x] Lane 옮기면 바로 반영되게
- [x] Lane 추가 바로 반영되게
- [x] Lane 이름 수정 바로 반영되게
- [x] Lane 삭제 바로 반영되게
